/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tapsecure.gui.panel;

import com.mycompany.tapsecure.objects.LogAbsensi; // Sekarang aman, tidak ada konflik nama lagi!
import com.mycompany.tapsecure.services.LogAbsensiService;
import com.mycompany.tapsecure.services.KaryawanService;
import com.mycompany.tapsecure.objects.Karyawan;
import com.mycompany.tapsecure.util.EncryptionUtils;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import com.mycompany.tapsecure.services.I18nService;

/**
 *
 * @author satria, vaena
 */
public class LogAbsensiPanel extends javax.swing.JPanel {

    /**
     * Creates new form LogAbsensi
     */
    public LogAbsensiPanel() {
        initComponents();
        
        applyLanguage();
        I18nService.registerListener(() -> applyLanguage());
        
        showData();
    }
    
    private void showData() {

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        LogAbsensiService service = new LogAbsensiService();
        KaryawanService karyawanService = new KaryawanService();

        List<LogAbsensi> listLog = service.getAllLog();

        if (listLog == null || listLog.isEmpty()) {
            return;
        }

        for (LogAbsensi log : listLog) {

            String idTampil = I18nService.get("log.anonymous");

            String hashedUid = log.getUidRfid();

            if (hashedUid != null && !hashedUid.isEmpty()) {

                Karyawan karyawan = karyawanService.findByUid(hashedUid);

                if (karyawan != null) {
                    idTampil = EncryptionUtils.decrypt(karyawan.getIdKaryawan());
                } else {
                    String shortUid = hashedUid.length() > 8
                            ? hashedUid.substring(0, 8)
                            : hashedUid;

                    idTampil = I18nService.get("log.uid") + ": " + shortUid;
                }
            }

            String waktu = log.getWaktuTap() != null
                    ? log.getWaktuTap().toString()
                    : "-";

            String statusCode = log.getStatus();
            String statusTampil = "IN".equals(statusCode)
                    ? I18nService.get("ui.status.in")
                    : I18nService.get("ui.status.out");

            model.addRow(new Object[]{
                idTampil,
                statusTampil,
                waktu
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Status", "Waktu"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void applyLanguage() {

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.setColumnIdentifiers(new Object[]{
            I18nService.get("log.id"),
            I18nService.get("log.status"),
            I18nService.get("log.time")
        });

        showData();
    }

}
