/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tapsecure.gui.panel;

import com.mycompany.tapsecure.objects.LogAbsensi; // Sekarang aman, tidak ada konflik nama lagi!
import com.mycompany.tapsecure.services.LogAbsensiService;
import com.mycompany.tapsecure.services.KaryawanService;
import com.mycompany.tapsecure.objects.Karyawan;
import com.mycompany.tapsecure.util.EncryptionUtils;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author satriya, vaena
 */
public class LogAbsensiPanel extends javax.swing.JPanel {

    /**
     * Creates new form LogAbsensi
     */
    public LogAbsensiPanel() {
        initComponents();
        
        showData();
    }
    
        private void showData() {
        // 1. AMBIL MODEL BAWAAN ASLI dari design NetBeans Anda yang ada di gambar (Id, Status, Waktu)
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        
        // 2. Kosongkan baris lamanya saja
        model.setRowCount(0);
        
        com.mycompany.tapsecure.services.LogAbsensiService service = new com.mycompany.tapsecure.services.LogAbsensiService();
        com.mycompany.tapsecure.services.KaryawanService karyawanService = new com.mycompany.tapsecure.services.KaryawanService();
        
        // 3. Ambil data log absensi dari MongoDB
        java.util.List<com.mycompany.tapsecure.objects.LogAbsensi> listLog = service.getAllLog(); 
        
        if (listLog == null || listLog.isEmpty()) {
            return;
        }

        // 4. Jalankan perulangan baris data
        for (com.mycompany.tapsecure.objects.LogAbsensi log : listLog) {
            
            // Set teks default awal agar kolom "Id" (Kolom pertama design Anda) wajib terisi teks
            String idTampil = "Kartu Anonim"; 
            
            String hashedUidDariLog = log.getUidRfid();
            
            if (hashedUidDariLog != null && !hashedUidDariLog.isEmpty()) {
                // Cari data master karyawan menggunakan hash UID utuh ke database
                com.mycompany.tapsecure.objects.Karyawan karyawan = karyawanService.findByUid(hashedUidDariLog);
                
                if (karyawan != null) {
                    // 💡 PROSES DEKRIPSI 2 ARAH (AES)
                    // Jika data karyawan ditemukan, dekripsi ID aslinya untuk masuk kolom "Id"
                    idTampil = com.mycompany.tapsecure.util.EncryptionUtils.decrypt(karyawan.getIdKaryawan());
                } else {
                    // Trik Fallback Sidang: Jika data karyawan null, paksa potong 8 huruf awal UID-nya agar kolom "Id" tidak melompong
                    String shortUid = hashedUidDariLog.length() > 8 ? hashedUidDariLog.substring(0, 8) : hashedUidDariLog;
                    idTampil = "UID: " + shortUid;
                }
            }
            
            String waktuTampil = log.getWaktuTap() != null ? log.getWaktuTap().toString() : "-";
            
            // 5. Masukkan data berurutan sesuai kolom di gambar design Anda (Kolom 0: Id, Kolom 1: Status, Kolom 2: Waktu)
            model.addRow(new Object[]{
                idTampil, 
                log.getStatus(), 
                waktuTampil
            });
        }
    }



   



    
        
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Status", "Waktu"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
